project:
  type: website
  output-dir: docs
website:
  title: "Theo's learning note"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hobby.qmd
      - about.qmd

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true

editor: visual

